# Experiment
project_name: "3_channels_abm"
run_name: "environment_optimization"
seed: 42
use_wandb: false
use_gpu: false

# Exploration settings
replicates: 50
n_trials: 1000
n_envs: 256 # Will be overridden by script to match total population
channel_y_name: "Belief"

# Parameters
x_dim: 2
y_dim: 2
n_agents: 10
n_targets: 1
targets_quality: "HM"
target_persistence: 20
target_movement_pattern: "levy"
relocation_interval: 200
max_steps: 1000
target_speed: 0.7

# Costs
cost_priv: 0.5
cost_belief: 0.1
cost_heading: 0.0
cost_pos: 0.0
cost_consensus: 0.01

# Noise & Selectivity
base_noise: 0.1
dist_noise_scale_priv: 0.1
dist_noise_scale_soc: 0.0  # beta belief
social_trans_scale: 0.01  # gamma belief
belief_selectivity_threshold: 100.0
consensus_selectivity_threshold: 1.0
bias_magnitude: 0.1

# Process Noise
process_noise_scale: 0.05
process_noise_scale_het_ratio: 0.0
process_noise_scale_het_scale: 10.0

# Other
momentum: 0.9
initialization_box_ratio: 0.5
min_dist_between_entities: 0.001
agent_radius: 0.05
continuous_actions: True
